### ISSUE TITLE
项目很适合，请问开源么

### ISSUE THREAD

**Issue by aaq1adqwe** [Un1kTeam/Un1kPoc#1]
老哥，你做的这个跟我之前很多想法一样，我想拿来做成团队中的漏洞管理和利用

**Comment by h4ckdepy** [comment]
师傅您好 过几天会把webapi的源码开源,并提交un1kpoc的jar包文件。
后续经过反复测试修复bug后,会连同jar包源码一同开源。现在还在熬夜修复一些异常问题，和编写docker容器。
